In [114]:
import pandas as pd
from functools import reduce

In [115]:
from pathlib import Path
import requests

def download_csv(csv_url, filename, datadir="./data/download/"):
    """
    Download a CSV file from a URL and save it locally.

    Parameters
    ----------
    csv_url : str
        Base URL of the server
    filename : str
        Name to save the file as
    datadir : str
        Directory where the file will be saved (default: ./download/data)
    """

    datadir = Path(datadir)
    datadir.mkdir(exist_ok=True)

    filepath = datadir / filename

    response = requests.get(csv_url, headers={"Content-type": "text/csv"})

    if response.status_code == 200:
        with open(filepath, "wb") as file:
            file.write(response.content)
        print(f"CSV file downloaded and saved as {filepath}")
    else:
        print(f"Failed to download the CSV file. Status code: {response.status_code}")

    return filepath

## Feature Descriptions

**Ref: Comparative microelectrode array data of the functional development of hPSC-derived and rat neuronal networks**

1. < data label >_meanfiringrate_by_active_electrodes.csv: mean firing rate of the active electrodes in a well

2. < data label >_STTC.csv: spike train tiling coefficient evaluating correlations between pairs of electrodes

3. < data label >_bursts_per_min.csv: average number of bursts per minute

4. < data label >_mean_dur.csv: average burst duration in seconds for the bursts captured

5. < data label >_mean_freq_in_burst.csv: average spike frequency for the bursts captured

6. < data label >_per_spikes_in_burst.csv: percentage of spikes participating in bursts

7. < data label >_mean_spikes_in_burst.csv: average number of spikes in bursts

In [116]:
base_url = "https://gin.g-node.org/NeuroGroup_TUNI/Comparative_MEA_dataset/raw/master/Data/hPSC_MEA3_Pharmacology/"
baseline_url = "hPSC_MEA3Baseline_DIV29/hPSC_MEA3Baseline_DIV29_meaRtools_output/"
treatment_url = "hPSC_MEA3Pharma_DIV29/hPSC_MEA3Pharma_DIV29_meaRtools_output/"

### Baseline

In [117]:
MFR_csv_url = base_url + baseline_url + "hPSC_120618_MEA3Baseline_meanfiringrate_by_active_electordes.csv" # Mean Firing Rate by Active Electrodes
STTC_csv_url = base_url + baseline_url + "hPSC_120618_MEA3Baseline_STTC.csv" # Spike Train Tiling Coefficient
burst_per_min_csv_url = base_url + baseline_url + "hPSC_120618_MEA3Baseline_bursts_per_min.csv" # Burst Per Minute
burst_duration_csv_url = base_url + baseline_url + "hPSC_120618_MEA3Baseline_mean_dur.csv" # Burst Duration
spike_freq_in_bursts_csv_url = base_url + baseline_url + "hPSC_120618_MEA3Baseline_mean_freq_in_burst.csv" # Spike Frequency Inside Bursts
percent_of_spikes_in_bursts_csv_url = base_url + baseline_url + "hPSC_120618_MEA3Baseline_per_spikes_in_burst.csv" # Percent of Spikes in Bursts
number_of_spikes_in_bursts_csv_url = base_url + baseline_url + "hPSC_120618_MEA3Baseline_mean_spikes_in_burst.csv" # Number of Spikes in Bursts

### Treatment

**Uncomment this part to do exacly the same process as the baseline, but for the treatment group.**

In [118]:
# MFR_csv_url = base_url + treatment_url + "hPSC_120618_MEA3Pharma_meanfiringrate_by_active_electordes.csv" # Mean Firing Rate by Active Electrodes
# STTC_csv_url = base_url + treatment_url + "hPSC_120618_MEA3Pharma_STTC.csv" # Spike Train Tiling Coefficient
# burst_per_min_csv_url = base_url + treatment_url + "hPSC_120618_MEA3Pharma_bursts_per_min.csv" # Burst Per Minute
# burst_duration_csv_url = base_url + treatment_url + "hPSC_120618_MEA3Pharma_mean_dur.csv" # Burst Duration
# spike_freq_in_bursts_csv_url = base_url + treatment_url + "hPSC_120618_MEA3Pharma_mean_freq_in_burst.csv" # Spike Frequency Inside Bursts
# percent_of_spikes_in_bursts_csv_url = base_url + treatment_url + "hPSC_120618_MEA3Pharma_per_spikes_in_burst.csv" # Percent of Spikes in Bursts
# number_of_spikes_in_bursts_csv_url = base_url + treatment_url + "hPSC_120618_MEA3Pharma_mean_spikes_in_burst.csv" # Number of Spikes in Bursts

In [119]:
csv_urls = [
    MFR_csv_url,
    STTC_csv_url,
    burst_per_min_csv_url,
    burst_duration_csv_url,
    spike_freq_in_bursts_csv_url,
    percent_of_spikes_in_bursts_csv_url,
    number_of_spikes_in_bursts_csv_url
]

filenames = [
    "MFR_baseline.csv",
    "STTC_baseline.csv",
    "bursts_per_min_baseline.csv",
    "burst_duration_baseline.csv",
    "spike_freq_in_bursts_baseline.csv",
    "percent_of_spikes_in_bursts_baseline.csv",
    "number_of_spikes_in_bursts_baseline.csv"
]

for csv_url, filename in zip(csv_urls, filenames):
    download_csv(csv_url, filename)

CSV file downloaded and saved as data/download/MFR_baseline.csv
CSV file downloaded and saved as data/download/STTC_baseline.csv
CSV file downloaded and saved as data/download/bursts_per_min_baseline.csv
CSV file downloaded and saved as data/download/burst_duration_baseline.csv
CSV file downloaded and saved as data/download/spike_freq_in_bursts_baseline.csv
CSV file downloaded and saved as data/download/percent_of_spikes_in_bursts_baseline.csv
CSV file downloaded and saved as data/download/number_of_spikes_in_bursts_baseline.csv

In [120]:
MFR_df = pd.read_csv("./data/download/MFR_baseline.csv")
MFR_df = MFR_df.rename(columns={"divDIV29": "MFR"})

STTC_df = pd.read_csv("./data/download/STTC_baseline.csv")
STTC_df = STTC_df.rename(columns={"divDIV29": "STTC"})

burst_per_min_df = pd.read_csv("./data/download/bursts_per_min_baseline.csv")
burst_per_min_df = burst_per_min_df.rename(columns={"divDIV29": "burst_per_min"})

burst_duration_df = pd.read_csv("./data/download/burst_duration_baseline.csv")
burst_duration_df = burst_duration_df.rename(columns={"divDIV29": "burst_duration"})

spike_freq_in_bursts_df = pd.read_csv("./data/download/spike_freq_in_bursts_baseline.csv")
spike_freq_in_bursts_df = spike_freq_in_bursts_df.rename(columns={"divDIV29": "spike_freq_in_bursts"})

percent_of_spikes_in_bursts_df = pd.read_csv("./data/download/percent_of_spikes_in_bursts_baseline.csv")
percent_of_spikes_in_bursts_df = percent_of_spikes_in_bursts_df.rename(columns={"divDIV29": "percent_of_spikes_in_bursts"})

number_of_spikes_in_bursts_df = pd.read_csv("./data/download/number_of_spikes_in_bursts_baseline.csv")
number_of_spikes_in_bursts_df = number_of_spikes_in_bursts_df.rename(columns={"divDIV29": "number_of_spikes_in_bursts"})

# Merge all dataframes on 'well' column
dfs = [
    MFR_df,
    STTC_df,
    burst_per_min_df,
    burst_duration_df,
    spike_freq_in_bursts_df,
    percent_of_spikes_in_bursts_df,
    number_of_spikes_in_bursts_df
]

features_baseline = reduce(lambda left, right: pd.merge(left, right, on=["well", "treatment"]), dfs)
features_baseline

,well,treatment,MFR,STTC,burst_per_min,burst_duration,spike_freq_in_bursts,percent_of_spikes_in_bursts,number_of_spikes_in_bursts
0,A5,NoTreatment,5.710159,0.468186,9.830769,0.557434,36.716393,60.348,24.255
1,A6,NoTreatment,5.086989,0.518162,7.504000,0.717445,37.701621,66.457,28.857
2,A7,NoTreatment,5.356592,0.196660,15.210000,0.578593,35.425549,62.207,21.357
3,A8,NoTreatment,3.426882,0.356629,6.621429,0.486556,35.993312,54.188,19.217
4,B5,NoTreatment,5.392085,0.432973,7.915000,1.112452,38.651003,77.417,39.603
5,B6,NoTreatment,5.112961,0.511215,7.058571,0.950356,38.962057,75.383,37.438
6,B7,NoTreatment,8.236042,0.478396,9.690000,0.984569,38.533903,82.338,45.495
7,B8,NoTreatment,9.088305,0.469130,8.329091,1.143225,40.529732,88.430,63.125
8,C5,NoTreatment,7.362940,0.427152,10.470000,0.722835,38.999289,78.271,41.296
9,C6,NoTreatment,4.620322,0.586544,7.720000,0.580672,39.504156,70.770,27.107
10,C7,NoTreatment,5.831956,0.470231,9.308000,0.626945,37.844681,71.460,28.673
11,C8,NoTreatment,5.417190,0.587311,7.573846,0.906071,37.160962,76.733,32.961
12,D5,NoTreatment,4.520946,0.533750,6.344000,0.832136,39.077536,71.955,32.850
13,D6,NoTreatment,3.902415,0.472324,6.092000,0.542762,38.946866,64.532,24.779
14,D7,NoTreatment,3.469903,0.448913,8.478462,0.459189,38.108127,60.473,18.274
15,D8,NoTreatment,5.426643,0.564612,9.802500,0.529578,37.289416,71.596,23.782
16,E5,NoTreatment,3.927637,0.516430,6.852857,0.919359,36.092189,72.089,26.581
17,E6,NoTreatment,3.939230,0.402371,9.309231,0.428992,35.480805,55.920,16.376
18,E7,NoTreatment,5.567709,0.515138,9.156923,0.712263,37.966086,72.170,28.372
19,E8,NoTreatment,6.054536,0.461955,8.072727,0.835146,39.828221,77.197,44.179
20,F5,NoTreatment,3.763785,0.454378,8.175000,0.488003,37.086620,55.597,19.191
21,F6,NoTreatment,6.196551,0.196229,23.593333,0.378800,36.106256,57.109,13.004
22,F7,NoTreatment,2.786077,0.156419,6.274286,0.384873,36.432518,25.776,13.731
23,F8,NoTreatment,4.120182,0.370692,8.123077,0.623337,35.973197,61.938,23.207

### Treatment

In [121]:
MFR_csv_url = base_url + treatment_url + "hPSC_120618_MEA3Pharma_meanfiringrate_by_active_electordes.csv" # Mean Firing Rate by Active Electrodes
STTC_csv_url = base_url + treatment_url + "hPSC_120618_MEA3Pharma_STTC.csv" # Spike Train Tiling Coefficient
burst_per_min_csv_url = base_url + treatment_url + "hPSC_120618_MEA3Pharma_bursts_per_min.csv" # Burst Per Minute
burst_duration_csv_url = base_url + treatment_url + "hPSC_120618_MEA3Pharma_mean_dur.csv" # Burst Duration
spike_freq_in_bursts_csv_url = base_url + treatment_url + "hPSC_120618_MEA3Pharma_mean_freq_in_burst.csv" # Spike Frequency Inside Bursts
percent_of_spikes_in_bursts_csv_url = base_url + treatment_url + "hPSC_120618_MEA3Pharma_per_spikes_in_burst.csv" # Percent of Spikes in Bursts
number_of_spikes_in_bursts_csv_url = base_url + treatment_url + "hPSC_120618_MEA3Pharma_mean_spikes_in_burst.csv" # Number of Spikes in Bursts

In [122]:
csv_urls = [
    MFR_csv_url,
    STTC_csv_url,
    burst_per_min_csv_url,
    burst_duration_csv_url,
    spike_freq_in_bursts_csv_url,
    percent_of_spikes_in_bursts_csv_url,
    number_of_spikes_in_bursts_csv_url
]

filenames = [
    "MFR_treatment.csv",
    "STTC_treatment.csv",
    "bursts_per_min_treatment.csv",
    "burst_duration_treatment.csv",
    "spike_freq_in_bursts_treatment.csv",
    "percent_of_spikes_in_bursts_treatment.csv",
    "number_of_spikes_in_bursts_treatment.csv"
]

for csv_url, filename in zip(csv_urls, filenames):
    download_csv(csv_url, filename)

CSV file downloaded and saved as data/download/MFR_treatment.csv
CSV file downloaded and saved as data/download/STTC_treatment.csv
CSV file downloaded and saved as data/download/bursts_per_min_treatment.csv
CSV file downloaded and saved as data/download/burst_duration_treatment.csv
CSV file downloaded and saved as data/download/spike_freq_in_bursts_treatment.csv
CSV file downloaded and saved as data/download/percent_of_spikes_in_bursts_treatment.csv
CSV file downloaded and saved as data/download/number_of_spikes_in_bursts_treatment.csv

In [123]:
MFR_df = pd.read_csv("./data/download/MFR_treatment.csv")
MFR_df = MFR_df.rename(columns={"divDIV29": "MFR"})

STTC_df = pd.read_csv("./data/download/STTC_treatment.csv")
STTC_df = STTC_df.rename(columns={"divDIV29": "STTC"})

burst_per_min_df = pd.read_csv("./data/download/bursts_per_min_treatment.csv")
burst_per_min_df = burst_per_min_df.rename(columns={"divDIV29": "burst_per_min"})

burst_duration_df = pd.read_csv("./data/download/burst_duration_treatment.csv")
burst_duration_df = burst_duration_df.rename(columns={"divDIV29": "burst_duration"})

spike_freq_in_bursts_df = pd.read_csv("./data/download/spike_freq_in_bursts_treatment.csv")
spike_freq_in_bursts_df = spike_freq_in_bursts_df.rename(columns={"divDIV29": "spike_freq_in_bursts"})

percent_of_spikes_in_bursts_df = pd.read_csv("./data/download/percent_of_spikes_in_bursts_treatment.csv")
percent_of_spikes_in_bursts_df = percent_of_spikes_in_bursts_df.rename(columns={"divDIV29": "percent_of_spikes_in_bursts"})

number_of_spikes_in_bursts_df = pd.read_csv("./data/download/number_of_spikes_in_bursts_treatment.csv")
number_of_spikes_in_bursts_df = number_of_spikes_in_bursts_df.rename(columns={"divDIV29": "number_of_spikes_in_bursts"})

# Merge all dataframes on 'well' column
dfs = [
    MFR_df,
    STTC_df,
    burst_per_min_df,
    burst_duration_df,
    spike_freq_in_bursts_df,
    percent_of_spikes_in_bursts_df,
    number_of_spikes_in_bursts_df
]

features_treatment = reduce(lambda left, right: pd.merge(left, right, on=["well", "treatment"]), dfs)
features_treatment

,well,treatment,MFR,STTC,burst_per_min,burst_duration,spike_freq_in_bursts,percent_of_spikes_in_bursts,number_of_spikes_in_bursts
0,A5,Gabazine,7.112287,0.702362,5.844000,1.077395,44.363821,84.921,66.231
1,A6,Gabazine,6.962891,0.808137,3.056250,2.148795,48.858721,90.451,123.709
2,A7,Gabazine,6.508021,0.448664,9.080000,0.768554,39.608284,78.050,39.127
3,A8,Gabazine,5.201775,0.686182,3.671250,1.385822,40.793304,83.317,70.749
4,B5,KainicAcid,3.539348,0.001633,31.368000,0.259723,34.775238,41.397,7.848
5,B6,KainicAcid,3.537483,0.018390,23.532000,0.242017,32.317899,27.596,6.966
6,B7,KainicAcid,4.934075,0.023459,31.050000,0.848409,40.872774,58.691,33.571
7,B8,KainicAcid,7.913338,0.011663,63.200000,0.369927,36.982098,60.529,12.127
8,C5,Control,7.629853,0.439265,8.210769,0.916327,39.357947,80.368,51.715
9,C6,Control,4.905969,0.668897,3.616000,1.833659,38.030005,82.002,71.290
10,C7,Control,5.494108,0.528646,5.505000,0.999850,37.344563,75.104,45.025
11,C8,Control,6.281997,0.658494,4.860000,1.936622,36.682743,85.256,71.646
12,D5,GABA,2.007019,0.072309,3.696923,0.236376,40.049930,22.302,8.951
13,D6,GABA,1.938051,0.007838,9.510000,0.226512,36.327899,8.837,7.042
14,D7,GABA,1.561728,0.076435,1.183636,0.385032,30.538122,11.667,11.742
15,D8,GABA,2.816994,0.009689,13.546667,0.297156,35.625920,42.444,9.428
16,E5,CNQX,1.115944,0.004510,0.600000,0.153153,41.688388,0.780,5.222
17,E6,CNQX,1.236328,0.004950,23.520000,0.204434,39.450210,16.677,6.843
18,E7,CNQX,2.205774,0.004888,9.274286,0.266223,38.600865,36.887,9.030
19,E8,CNQX,2.760692,0.015674,22.220000,0.264809,36.259114,30.761,8.410
20,F5,D-AP5,0.941928,0.003481,0.120000,0.204524,26.470639,0.254,5.091
21,F6,D-AP5,1.886334,0.002619,1.740000,0.195510,34.949044,1.437,6.155
22,F7,D-AP5,1.357670,0.001737,2.400000,0.177364,39.613485,2.594,5.722
23,F8,D-AP5,1.355063,0.005820,NaN,NaN,NaN,0.000,NaN

In [124]:
features_treatment.to_csv("./data/processed/features_treatment.csv", index=False)
features_baseline.to_csv("./data/processed/features_baseline.csv", index=False)